name: Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, ec]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      run: make lint
  test:
    runs-on: [self-hosted, ec]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # Need full history for version detection
      with:
        fetch-depth: 0
    - name: Test
      run: make test

# vim: ts=2:sw=2
